using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;

namespace StoryHub.DAL.Model
{
    class Enums
    {
        
    }

    /// <summary>
    /// Enum for possible genres.
    /// </summary>
    public enum Genre 
    { 
        fantasy,
        horror,
        scifi,
        romantic,
    }

    /// <summary>
    /// Enum for possible types of stories.
    /// Simple story - only formated text with one picture.
    /// Voted story - only formated text with possible picture. There are possibilities of voting in the end of the story.
    /// Comics - pictures only.
    /// Voice story - red story.
    /// </summary>
    public enum Type
    {
        simple_story,
        voted_story,
        comics,
        voice_story,
    }

    /// <summary>
    /// Enumertion of genders.
    /// </summary>
    public enum Gender
    { 
        None,
        Male,
        Female,
        Shklee,
    }

    /// <summary>
    /// Enumeration of nationalities in the world.
    /// </summary>
    public enum Nationality
    { 
        None,
        Afghan,
        Albanian,
        Algerian,
        American,
        Andorran,
        Angolan,
        Antiguans,
        Argentinean,
        Armenian,
        Australian,
        Austrian,
        Azerbaijani,
        Bahamian,
        Bahraini,
        Bangladeshi,
        Barbadian,
        Barbudans,
        Batswana,
        Belarusian,
        Belgian,
        Belizean,
        Beninese,
        Bhutanese,
        Bolivian,
        Bosnian,
        Brazilian,
        British,
        Bruneian,
        Bulgarian,
        Burkinabe,
        Burmese,
        Burundian,
        Cambodian,
        Cameroonian,
        Canadian,
        Cape_Verdean,
        Central_African,
        Chadian,
        Chilean,
        Chinese,
        Colombian,
        Comoran,
        Congolese,
        Costa_Rican,
        Croatian,
        Cuban,
        Cypriot,
        Czech,
        Danish,
        Djibouti,
        Dominican,
        Dutch,
        East_Timorese,
        Ecuadorean,
        Egyptian,
        Emirian,
        Equatorial_Guinean,
        Eritrean,
        Estonian,
        Ethiopian,
        Fijian,
        Filipino,
        Finnish,
        French,
        Gabonese,
        Gambian,
        Georgian,
        German,
        Ghanaian,
        Greek,
        Grenadian,
        Guatemalan,
        Guinea_Bissauan,
        Guinean,
        Guyanese,
        Haitian,
        Herzegovinian,
        Honduran,
        Hungarian,
        I_Kiribati,
        Icelander,
        Indian,
        Indonesian,
        Iranian,
        Iraqi,
        Irish,
        Israeli,
        Italian,
        Ivorian,
        Jamaican,
        Japanese,
        Jordanian,
        Kazakhstani,
        Kenyan,
        Kittian_and_Nevisian,
        Kuwaiti,
        Kyrgyz,
        Laotian,
        Latvian,
        Lebanese,
        Liberian,
        Libyan,
        Liechtensteiner,
        Lithuanian,
        Luxembourger,
        Macedonian,
        Malagasy,
        Malawian,
        Malaysian,
        Maldivan,
        Malian,
        Maltese,
        Marshallese,
        Mauritanian,
        Mauritian,
        Mexican,
        Micronesian,
        Moldovan,
        Monacan,
        Mongolian,
        Moroccan,
        Mosotho,
        Motswana,
        Mozambican,
        Namibian,
        Nauruan,
        Nepalese,
        New_Zealander,
        Nicaraguan,
        Nigerian,
        Nigerien,
        North_Korean,
        Northern_Irish,
        Norwegian,
        Omani,
        Pakistani,
        Palauan,
        Panamanian,
        Papua_New_Guinean,
        Paraguayan,
        Peruvian,
        Polish,
        Portuguese,
        Qatari,
        Romanian,
        Russian,
        Rwandan,
        Saint_Lucian,
        Salvadoran,
        Samoan,
        San_Marinese,
        Sao_Tomean,
        Saudi,
        Scottish,
        Senegalese,
        Serbian,
        Seychellois,
        Sierra_Leonean,
        Singaporean,
        Slovakian,
        Slovenian,
        Solomon_Islander,
        Somali,
        South_African,
        South_Korean,
        Spanish,
        Sri_Lankan,
        Sudanese,
        Surinamer,
        Swazi,
        Swedish,
        Swiss,
        Syrian,
        Taiwanese,
        Tajik,
        Tanzanian,
        Thai,
        Togolese,
        Tongan,
        Trinidadian_or_Tobagonian,
        Tunisian,
        Turkish,
        Tuvaluan,
        Ugandan,
        Ukrainian,
        Uruguayan,
        Uzbekistani,
        Venezuelan,
        Vietnamese,
        Welsh,
        Yemenite,
        Zambian,
        Zimbabwean,
    }
    
}
